[package]
name = "zombot"
version = "1.0.0"

[dependencies]
serde_derive = "1.0.43"
serde = "1.0.43"
serde_json = "1.0.16"

rand = "0.4.2"
time = "0.1.4"
rayon = "1.0.1"


[features]
benchmarking = []
single-threaded = []
